### ISSUE TITLE
JPG's with transparency have rendering issues

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-storage#48]
### What is the expected behavior?
Even if the JPG has transparency, it should render correctly.

### What is the actual behavior?
There is a white tinge to the image when it is recalled from Storage due to rendering discrepancies.

### What steps can be taken to replicate the problem?
Attached to this defect is the original file, and here is where you can find it in Storage: https://storage.googleapis.com/risemedialibrary-556323b8-984c-4127-aa08-4d73d019bcb8/Pictures/Villa%20Toscana%20digital%20signage_V.jpg

![Villa Toscana digital signage_V](https://user-images.githubusercontent.com/6862256/91608237-291bf480-e943-11ea-9ac9-3d0cf7b3d5db.jpg)

**Comment by tejohnso** [comment]
@robb-price This is a rare edge case with a jpeg containing transparency which isn't a standard jpeg. Unless it's reocurring, I think we should close without investing any effort to try to handle this scenario.

**Comment by robb-price** [comment]
@tejohnso That is fine with me. I have only had 1 user bring this up, and the workaround was simple.

**Comment by robb-price** [comment]
Reopening this, as we have had a second instance.

Patrick will add details to this bug about the second instance.

**Comment by PatrickA-RiseVision** [comment]
It looks like this is probably happening during compression.  I can replicate it with an image a customer sent me.  This is happening to all JPGs she tries to upload.  Probably, she is using a tool like Photoshop to add a layer over the image and then saving it as a JPG.  If I re-save the image as PNG and upload both, then immediately download both, there's a noticeable difference in coloration.

![image](https://user-images.githubusercontent.com/40774237/95344399-fba25f00-088f-11eb-9c5f-401d0fd8b7ad.png)

**Comment by tejohnso** [comment]
We'll try to detect the transparency and avoid compression in that case.

**Comment by alanclayton** [comment]
![masthead_main](https://user-images.githubusercontent.com/6854911/97252711-a4314800-17d8-11eb-8c8a-ae8ee95aa985.jpg)

**Comment by btfrise** [comment]
[Discussed](https://docs.google.com/document/d/1iJvOQhAQO5BY60Fb8TD997w2xGL05j0ZGM7NgeidyeA/edit), we are closing

**Comment by tejohnso** [comment]
[Link](https://docs.google.com/document/d/1EI0kyKdRMNxMN0Buvt9bzJ8UMSHpNL82HZlRVm6JKCk/edit#) to potential solution that was pass on during discussions. This defect is a rare edge case with a reasonable workaround and a potentially complex fix.

[Link](https://rise-vision-inc.slack.com/archives/CCELMSZFZ/p1603810372130100) to close confirmation
