### ISSUE TITLE
Storage compression causes artifacting

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-storage#50]
### What is the expected behavior?
When an image is uploaded to Rise Storage, it is converted/compressed but maintains the same quality.

### What is actually happening
When an image is uploaded to Rise Storage, it's conversion/compression causes some artifacts.

### What steps can be taken to replicate the issue?
Attached to this defect is an original file. After uploading to Rise Storage you'll notice artifacts within the white fonts.
https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/Folie1%20Kopie.jpeg
![Folie1 Kopie](https://user-images.githubusercontent.com/8458926/93924344-37f38e00-fcda-11ea-9a4c-d093f60cc55a.jpeg)

**Comment by btfrise** [comment]
[Discussed](https://docs.google.com/document/d/1iJvOQhAQO5BY60Fb8TD997w2xGL05j0ZGM7NgeidyeA/edit), we are closing.

**Comment by tejohnso** [comment]
[Link](https://docs.google.com/document/d/1EI0kyKdRMNxMN0Buvt9bzJ8UMSHpNL82HZlRVm6JKCk/edit#) to potential solution that was pass on during discussions. This defect is a rare edge case with a reasonable workaround and a potentially complex fix.

[Link](https://rise-vision-inc.slack.com/archives/CCELMSZFZ/p1603810372130100) to close confirmation
