### ISSUE TITLE
Storage compression causes lower quality video

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-storage#52]
### What is the expected behavior?
When a video is uploaded to Rise Storage, it should maintain the same quality as the original file.

### What is actually happening?
When a video is uploaded to Rise Storage, the video quality isn't as good as the original file. Visual artifacts and stuttering can be seen in the file on Rise Storage.

### What steps can be taken to replicate the issue?
Original files are available at
https://drive.google.com/file/d/16FjInfPZsMHi-llp_yTCAIoHPO_65kQV/view?usp=sharing
https://drive.google.com/file/d/1xTuHj3qtTiA1Y3tCsaMTc0aKQ77H8wb8/view?usp=sharing

After uploading to Rise Storage you'll notice artifacts on converted video. Also the bitrate has gone from 6.5mbit to 2mbit.

**Comment by btfrise** [comment]
[Discussed](https://rise-vision-inc.slack.com/archives/CCELMSZFZ/p1603810372130100), closing.

**Comment by tejohnso** [comment]
[Link](https://docs.google.com/document/d/1EI0kyKdRMNxMN0Buvt9bzJ8UMSHpNL82HZlRVm6JKCk/edit#) to potential solution that was pass on during discussions. This defect is a rare edge case with a reasonable workaround and a potentially complex fix.

[Link](https://rise-vision-inc.slack.com/archives/CCELMSZFZ/p1603810372130100) to close confirmation
