### ISSUE TITLE
Images uploaded to Rise Storage not rotated correctly

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-storage#53]
**Expected Behavior**
Images uploaded to Rise Storage upload with the correct orientation every time. It should match the orientation that is shown on the device that the image is uploaded from.

**Actual Behavior**
Images uploaded to Rise Storage are appearing at the wrong orientation.

**Steps to Reproduce**
Watch [this video](https://drive.google.com/file/d/1p_sGrkgbaLBtEUc8SHmyQa40gEAZjWjK/view?usp=sharing).

**Comment by tejohnso** [comment]
EXIF data is deliberately stripped for consistency across Storage UI and content presentation. See [decision record](https://github.com/Rise-Vision/decision-records/blob/master/ADRs/exif-handling.md).
